Sojourn de-LARPification Project
Equinox-SS13/equinox-sojourn pull request #26
Opened 2024-08-11 01:30 UTC by Draganfrukts

## About The Pull Request

Eliminate a bunch of post-soviet LARP, improve some sprites, and standardize a lot of descriptions. Also remove weird racist shit.

Dear Sojourn coders,
https://en.wikipedia.org/wiki/Apartheid
https://en.wikipedia.org/wiki/Rhodesia#Sanctions
</details>

## Changelog
:cl:
WIP
/:cl:

2024-08-11 03:50 UTC, Kilmented commented
"rhodesia":
![image](https://github.com/user-attachments/assets/28cb5943-6a91-458c-a0f8-0a49766988bb)

2024-08-12 06:34 UTC, EmilitiaEnnehrt commented
Thank you, if you need sprites and ideas let me know. Might be good to look into uniforms too or in a separate PR.

2024-08-13 00:13 UTC, Hawk-v3 commented
This PR is still marked as Draft @Draganfrukts 
![image](https://github.com/user-attachments/assets/d7b9e19e-6b89-4cbe-a2cc-10f135e6f615)

2024-08-17 03:35 UTC, Draganfrukts commented
> This PR is still marked as Draft @Draganfrukts ![image](https://private-user-images.githubusercontent.com/1232355/357237368-d7b9e19e-6b89-4cbe-a2cc-10f135e6f615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjU1MzgsIm5iZiI6MTcyMzg2NTIzOCwicGF0aCI6Ii8xMjMyMzU1LzM1NzIzNzM2OC1kN2I5ZTE5ZS02Yjg5LTRjYmUtYTJjYy0xMGYxMzVlNmY2MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDMyNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcyODU4NjQ5YjRjMjQ5ZDgzNTFlMDhmNWI2OTgzODg2M2MyYWY5Nzc2ODU4ZjYxZjYxZTgwNjUyNDM1ODYwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7saMD5zbf5-DojroT8B4s8o6YNaTsWcZuoKMmTk8OrU)

Work in progress.

2024-08-20 18:54 UTC, Draganfrukts commented on code/modules/projectiles/guns/projectile/automatic/sts.dm
Notice: Héristal Factory is unlike Fabrique Nationale Herstal

2024-08-20 18:56 UTC, Draganfrukts commented on code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
> +	desc = "The \"M13A\" is versatile, reliable battle rifle chambered in 8.6x70mm - most commonly seen in the hands of SolFed infantrymen. It's especially hard to control without servos or a static mou
```suggestion
	desc = "The \"M13A\" is a versatile, reliable battle rifle chambered in 8.6x70mm - most commonly seen in the hands of SolFed infantrymen. It's especially hard to control without servos or a static mount."
```

2024-09-10 16:25 UTC, Takykardi commented
Any forward movement on this? As it stands, it's ready to merge, just waiting to be marked as good to go.

2025-01-27 01:56 UTC, Takykardi approved these changes
Description changes seem to be in order. Zero tolerance for Rhodesia or its supporters. Assuming the sprite changes were the ones shown off, those are also good to go. 

Edit: disregard the above. I forgot to run the tests, which came up with the error described in the below change request.

2025-01-27 02:06 UTC, Takykardi requested changes
Disregard the above approve, I forgot to run the tests first. Tests are failing.

2025-01-27 02:06 UTC, Takykardi commented on code/modules/projectiles/guns/projectile/automatic/mac.dm
> +/* /obj/item/gun/projectile/automatic/mac/croon
This is causing a compile error. code/game/objects/random/guns.dm, line 122 is calling for this obj but you've commented it out. Please resolve by either removing the comment here or removing the call in the above file.

2025-01-27 13:14 UTC, valkyria-gk commented on code/modules/projectiles/guns/projectile/automatic/mac.dm
> + */
This is failing the compile.

2025-01-27 15:26 UTC, Draganfrukts commented
fuck my chud incel life

2025-01-27 17:09 UTC, valkyria-gk submitted a review, later dismissed
Issues fixed. Back to TM it goes.

2025-02-13 21:52 UTC, Hawk-v3 commented on code/modules/projectiles/guns/energy/laser/abdicator.dm
> +		list(mode_name="flare shell", mode_desc="fires an illuminating flare of variable colors", projectile_type=/obj/item/projectile/bullet/flare/choas, charge_cost=100, icon="grenade"),
This line, Dragonfruits

2025-02-13 22:16 UTC, Hawk-v3 commented
Lovely, all pass. Did you have any other work you wanted to do, or is this ready?

2025-02-13 23:41 UTC, Draganfrukts commented
> Lovely, all pass. Did you have any other work you wanted to do, or is this ready?

As it stands I'd like for this to remain a testmerge. The branch and the PR let me keep steady track of my work. Once I'm entirely done with the guns and I move on to equipment I'll let you know to get it for a full merge.

2025-02-17 01:46 UTC, Awesome4Real commented
The "operator" shotguns that the marshals get have lost their marshal's color scheme. Is this an intentional change?

2025-02-22 15:15 UTC, valkyria-gk commented
I think I will have to be chief here. We are well over 500 lines of code changed and closing in to 150 files changes. I would appreciate to have this commit to be split up to smaller subunits. That we can review the assets individually when you feel you are ready to go submit them. 

As this stands right now, this is an acceptable set up to test all the changes in one convenient test-merge. But the amount of content altered begs for a finer review. In my opinion.

2025-02-23 19:36 UTC, Takykardi commented
Seconding this. At least breaking it up into two parts, the sprites and the gun descriptions.

2025-02-24 12:53 UTC, Draganfrukts commented
> The "operator" shotguns that the marshals get have lost their marshal's color scheme. Is this an intentional change?

Answered in Discord earlier (Basically yes)
_______
> I think I will have to be chief here. We are well over 500 lines of code changed and closing in to 150 files changed. I would appreciate to have this commit to be split up to smaller subunits. That we can review the assets individually when you feel you are ready to go submit them. 
@valkyria-gk 

> At least breaking it up into two parts, the sprites and the gun descriptions.
@Takykardi 

While I partially addressed this in Discord, I'll address it again for the sake of posterity & accessibility when viewing the PR itself

As stated in another conversation about it,
"I wouldn't know where to start with atomizing and it would make development slower 4 me, as it stands I can ping pong around the same branch on my PC & see all the changed files & what have you"

Generally these requests should've come in weeks earlier when the sprite changes were few and far between and it would've been easy_(er)_ to keep all the sprite changes to a separate branch with it's own PR.
Now that the descriptions have been fully completed, I'm working getting rid of all the bum LARP like the bare M16s & this means I can easily match all the changes to their descriptions with the sprites without having to zip around from branch to branch.

It should be noted that the decision to keep all the clothing/armor changes on standby until this PR itself is finished instead of tacking it on was a deliberate decision because we knew "Hey this PR is big enough on it's own"

I'm going to be posting a resprite masterlist (An image with all the substantial changes) as I near completion. As it stands, a grand majority of these re-sprites are some changes to shading or some shape adjustments to make the gun look nicer instead of total overhauls.

2025-02-26 17:49 UTC, benj8560 commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "A bullpup submachine gun that could be chambered in either .35 Auto or 10mm Magnum by virtue of it's peculiar hybrid barrel threads."
```suggestion
	desc = "A bullpup submachine gun that could be chambered in either 9mm Auto or 10mm Magnum by virtue of it's peculiar hybrid barrel threads."
```

2025-02-26 17:49 UTC, benj8560 commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "A C20r SMG frame. It can be chambered in either .35 Auto or 10mm Magnum."
```suggestion
	desc = "A C20r SMG frame. It can be chambered in either 9mm Auto or 10mm Magnum."
```

2025-02-26 17:49 UTC, benj8560 commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "A bullpup submachine gun that could be chambered in either .35 Auto or 10mm Magnum by virtue of it's peculiar hybrid barrel threads. This one seems to be a colony-made reproduction."
```suggestion
	desc = "A bullpup submachine gun that could be chambered in either 9mm Auto or 10mm Magnum by virtue of it's peculiar hybrid barrel threads. This one seems to be a colony-made reproduction."
```

2025-02-26 17:49 UTC, benj8560 commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "A reverse engineered C-20r frame. It can be chambered in either .35 Auto or 10mm Magnum."
```suggestion
	desc = "A reverse engineered C-20r frame. It can be chambered in either 9mm Auto or 10mm Magnum."
```
Noticed this. Lets not unstandardized are standard

2025-03-04 17:14 UTC, WeNeedMorePhoron reviewed
Per discussion on Discord - this PR will be split into one for the description and one for the sprites changes.

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/laser/cog.dm
> -	desc = "A Greyson Positronic design, cheap and widely produced. In the distant past - this was the main weapon of low-rank police forces, billions of copies of this gun were made. They are ubiquitou
i actually kind of like this GP flavour description, i think we should keep it

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/laser/disco_vazer.dm
> -	desc = "This conversion of the \"Texan\" that enables it to shoot lasers. Unlike in other laser weapons, the process of creating a laser is based on a chain reaction of localized micro-explosions. \
soulless removal. disco vaser description and name ('lasblender' is AWESOME) is cool.

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
> +		list(mode_name="Plasma", mode_desc="Hard hitting plasma bolt that melts flesh and armor", projectile_type=/obj/item/projectile/plasma/heavy, fire_sound='sound/weapons/energy/incinerate.ogg', fire_d
```suggestion
		list(mode_name="plasma", mode_desc="Hard hitting plasma bolt that melts flesh and armor", projectile_type=/obj/item/projectile/plasma/heavy, fire_sound='sound/weapons/energy/incinerate.ogg', fire_delay = 9, icon="destroy", projectile_color = "#2bd37f"),
```

firemodes should be lowercase

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
> +		list(mode_name="EMP", mode_desc="An Ionized thoroid that disables electronics", projectile_type=/obj/item/projectile/ion, fire_sound='sound/effects/supermatter.ogg', fire_delay = 25, icon="stun", p
```suggestion
		list(mode_name="ion", mode_desc="An ionizing shot that disables electronics", projectile_type=/obj/item/projectile/ion, fire_sound='sound/effects/supermatter.ogg', fire_delay = 25, icon="stun", projectile_color = "#99ffb2"),
```

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/excubitor.dm
> +		list(mode_name="grenade", mode_desc="Fire a fragmenting explosive thoroid", projectile_type=/obj/item/projectile/bullet/grenade/frag/nt, charge_cost=30000, icon="grenade"),
```suggestion
		list(mode_name="grenade", mode_desc="fires a frag biomatter-shell", projectile_type=/obj/item/projectile/bullet/grenade/frag/nt, charge_cost=30000, icon="grenade"),
```
it always eats the (biomatter) cell to fire grenade shot, so i think the old description is actually more... descriptive

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/plasma.dm
> +		list(mode_name="Charged Plasma", mode_desc="Fire a strong plasma bolt", projectile_type=/obj/item/projectile/plasma/aoe/heat/strong, fire_sound='sound/weapons/energy/incinerate.ogg', fire_delay=20,
```suggestion
		list(mode_name="heavy plasma", mode_desc="Fire a strong plasma bolt", projectile_type=/obj/item/projectile/plasma/aoe/heat/strong, fire_sound='sound/weapons/energy/incinerate.ogg', fire_delay=20, charge_cost=200, icon="destroy", projectile_color = "#b3ff00"),		//Cool it with the religious zealotry remarks
```

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/plasma.dm
> +		list(mode_name="Plasma", mode_desc="Fire a light plasma bolt", mode_type = /datum/firemode/automatic, projectile_type=/obj/item/projectile/plasma, fire_sound='sound/weapons/energy/vaporize.ogg', fi
```suggestion
		list(mode_name="plasma", mode_desc="Fire a light plasma bolt", mode_type = /datum/firemode/automatic, projectile_type=/obj/item/projectile/plasma, fire_sound='sound/weapons/energy/vaporize.ogg', fire_delay=4, charge_cost=35, icon="burst", projectile_color = "#29c476"),
```

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/plasma.dm
> +		list(mode_name="Maraud", mode_desc="A plasma thoroid with enough energy behind it to melt plasteel.", projectile_type=/obj/item/projectile/plasma/heavy/super_heavy, fire_sound='sound/weapons/energy
```suggestion
		list(mode_name="superheated plasma", mode_desc="A plasma bolt with enough energy behind it to melt plasteel.", projectile_type=/obj/item/projectile/plasma/heavy/super_heavy, fire_sound='sound/weapons/energy/pulse.ogg', fire_delay=5, icon="kill", projectile_color = "#33ff00"),
```

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/variant.dm
> +		list(mode_name = "Standard", mode_desc="Fire a single bolt of ionized hydrogen.", projectile_type = /obj/item/projectile/hydrogen/pistol, fire_sound = 'sound/weapons/energy/hydrogen.ogg', icon = "d
```suggestion
		list(mode_name = "standard", mode_desc="Fire a single bolt of ionized hydrogen.", projectile_type = /obj/item/projectile/hydrogen/pistol, fire_sound = 'sound/weapons/energy/hydrogen.ogg', icon = "destroy", heat_per_shot = 25, use_plasma_cost = 10),
```

2025-03-05 09:35 UTC, lolman360 commented on code/modules/projectiles/guns/energy/plasma/variant.dm
> +		list(mode_name = "Unstable", mode_desc="Fire a large bolt of ionized hydrogen.", projectile_type = /obj/item/projectile/hydrogen/pistol/max, fire_sound = 'sound/weapons/energy/hydrogen_heavy.ogg',
```suggestion
		list(mode_name = "unstable", mode_desc="Fire an unstable, exploding bolt of ionized hydrogen.", projectile_type = /obj/item/projectile/hydrogen/pistol/max, fire_sound = 'sound/weapons/energy/hydrogen_heavy.ogg', icon = "vaporize", heat_per_shot = 40, use_plasma_cost = 20)
```

2025-03-05 11:52 UTC, Draganfrukts commented on code/modules/projectiles/guns/energy/laser/cog.dm
> -	desc = "A Greyson Positronic design, cheap and widely produced. In the distant past - this was the main weapon of low-rank police forces, billions of copies of this gun were made. They are ubiquitou
Greyson is being axed and re-lored.

2025-03-05 11:54 UTC, Draganfrukts commented on code/modules/projectiles/guns/energy/laser/disco_vazer.dm
> -	desc = "This conversion of the \"Texan\" that enables it to shoot lasers. Unlike in other laser weapons, the process of creating a laser is based on a chain reaction of localized micro-explosions. \
I don't care about soul. Most of us don't. Things change.

2025-03-05 11:57 UTC, Draganfrukts commented on code/modules/projectiles/guns/projectile/automatic/bastard.dm
> +	name = "\"Bastard\" light machine gun"
It's only the gun from Metro in appearance. It doesn't reflect this mechanically whatsoever. It's also likely on the chopping block.

2025-03-05 11:57 UTC, Draganfrukts commented on code/modules/projectiles/guns/projectile/automatic/drozd.dm
> +	name = "\"Thrush\" SMG"
We're keeping foreign naming to a minimum. Especially colony weapons.

2025-03-05 11:59 UTC, Draganfrukts commented on code/modules/projectiles/guns/projectile/boltgun/scout.dm
> +	name = "\"Magnum\" sniper rifle"
\"Magnum\" _**sniper rifle**_

It makes itself clear.

2025-03-05 12:01 UTC, Draganfrukts commented on code/modules/projectiles/guns/projectile/revolver/breakaction.dm
> +	name = "\"Matylda\" autorevolver"
[Source](https://en.wikipedia.org/wiki/Mateba_Autorevolver)

The Mateba Model 6 Unica (often known simply as the Mateba or the Mateba Autorevolver) is a recoil operated semi-automatic revolver, one of only a few of this type ever produced.
![image](https://github.com/user-attachments/assets/584bd742-6feb-4b97-8d6e-201bf01bdd0d)

A very real gun, and a very niche one at that. No special treatment for it.

2025-03-05 13:22 UTC, Draganfrukts commented on code/modules/projectiles/guns/projectile/boltgun/scout.dm
> +	name = "\"Magnum\" sniper rifle"
Context matters. "10mm magnum" is almost entirely unlike "Magnum sniper rifle"
This is a non-issue.

2025-03-05 13:28 UTC, Draganfrukts commented on code/modules/projectiles/guns/energy/plasma/plasma.dm
> +		list(mode_name="Maraud", mode_desc="A plasma thoroid with enough energy behind it to melt plasteel.", projectile_type=/obj/item/projectile/plasma/heavy/super_heavy, fire_sound='sound/weapons/energy
Mistype of Toroid; a ring of plasma. (And more importantly, what plasma guns actually shoot)
Fixed.

2025-03-06 13:47 UTC, Draganfrukts commented
### This PR is being continued respectiively in #156 & #157

2025-03-06 13:47 UTC, closed without merging